solver_options:
    regularization: 1e-2
    back_end: qpoases
    front_end: ihqp
    nhqp_min_sv_ratio: 0.05


stack:
    -
      - Wheel1
      - Wheel2
      - Wheel3
      - Wheel4
    -
      - Postural

constraints: [JointLimits, Collision]


JointLimits:
    type: JointLimits
    limits:
      j_arm2_4: [-2.4, -0.6]
      j_arm1_4: [-2.4, -0.6]

Collision:
    type: CollisionConstraint
    lib_name: libcartesio_collision_support.so
    bound_scaling: 0.1
    distance_threshold: 0.02
    max_pairs: 150
    collision_urdf_path: $(rospack find centauro_urdf)/urdf/centauro_capsule.urdf
    collision_srdf_path: $(rospack find centauro_srdf)/srdf/centauro_capsule.srdf

Wheel1:
    type: Cartesian
    distal_link: wheel_1
    indices: [2, 3, 4, 5]

Wheel2:
    type: Cartesian
    distal_link: wheel_2
    indices: [2, 3, 4, 5]

Wheel3:
    type: Cartesian
    distal_link: wheel_3
    indices: [2, 3, 4, 5]

Wheel4:
    type: Cartesian
    distal_link: wheel_4
    indices: [2, 3, 4, 5]

Postural:
    type: Postural
    lambda: 0.01
    weight: 1.0
