
q_parking_2:
  hip_yaw_1: -0.75
  hip_yaw_2: 0.75
  hip_yaw_3: 0.75
  hip_yaw_4: -0.75
  hip_pitch_1: -1.57
  hip_pitch_2: 1.57
  hip_pitch_3: 1.57
  hip_pitch_4: -1.57
  knee_pitch_1: -2.4
  knee_pitch_2: 2.4
  knee_pitch_3: 2.4
  knee_pitch_4: -2.4
  ankle_pitch_1: -0.84
  ankle_pitch_2: 0.84
  ankle_pitch_3: 0.84
  ankle_pitch_4: -0.84
  ankle_yaw_1: 0.0
  ankle_yaw_2: 0.0
  ankle_yaw_3: 0.0
  ankle_yaw_4: 0.0

q_parking_3:
  ankle_pitch_1: -2.4
  ankle_pitch_2: 2.4
  ankle_pitch_3: 2.4
  ankle_pitch_4: -2.4

q_unparking:
  hip_pitch_1: -1.57
  hip_pitch_2: 1.57
  hip_pitch_3: 1.57
  hip_pitch_4: -1.57
  knee_pitch_1: -2.4
  knee_pitch_2: 2.4
  knee_pitch_3: 2.4
  knee_pitch_4: -2.4
  ankle_pitch_1: -0.84
  ankle_pitch_2: 0.84
  ankle_pitch_3: 0.84
  ankle_pitch_4: -0.84
  ankle_yaw_1: 0.0
  ankle_yaw_2: 0.0
  ankle_yaw_3: 0.0
  ankle_yaw_4: 0.0

q_homing:
  hip_yaw_1: -0.75
  hip_yaw_2: 0.75
  hip_yaw_3: 0.75
  hip_yaw_4: -0.75
  ankle_pitch_1: -0.302
  ankle_pitch_2: 0.302
  ankle_pitch_3: 0.302
  ankle_pitch_4: -0.302
  hip_pitch_1: -1.25
  hip_pitch_2: 1.25
  hip_pitch_3: 1.25
  hip_pitch_4: -1.25
  knee_pitch_1: -1.56
  knee_pitch_2: 1.56
  knee_pitch_3: 1.56
  knee_pitch_4: -1.56
  d435_head_joint: 0.0
  j_arm1_1: 0.52
  j_arm1_2: 0.32
  j_arm1_3: 0.28
  j_arm1_4: -2.24
  j_arm1_5: 0.05
  j_arm1_6: -0.78
  j_arm2_1: 0.52
  j_arm2_2: -0.32
  j_arm2_3: -0.28
  j_arm2_4: -2.24
  j_arm2_5: -0.05
  j_arm2_6: -0.78

q_boxing_2:
  hip_yaw_1: 0.0
  hip_yaw_2: 0.0
  hip_yaw_3: 0.0
  hip_yaw_4: 0.0
  hip_pitch_1: -1.57
  hip_pitch_2: 1.57
  hip_pitch_3: 1.57
  hip_pitch_4: -1.57
  knee_pitch_1: -2.4
  knee_pitch_2: 2.4
  knee_pitch_3: 2.4
  knee_pitch_4: -2.4
  ankle_pitch_1: -0.84
  ankle_pitch_2: 0.84
  ankle_pitch_3: 0.84
  ankle_pitch_4: -0.84
  ankle_yaw_1: 0.0
  ankle_yaw_2: 0.0
  ankle_yaw_3: 0.0
  ankle_yaw_4: 0.0

q_boxing_3:
  ankle_pitch_1: -2.4
  ankle_pitch_2: 2.4
  ankle_pitch_3: -0.74
  ankle_pitch_4: 0.74

q_unboxing:
  hip_pitch_1: -1.57
  hip_pitch_2: 1.57
  hip_pitch_3: 1.57
  hip_pitch_4: -1.57
  knee_pitch_1: -2.4
  knee_pitch_2: 2.4
  knee_pitch_3: 2.4
  knee_pitch_4: -2.4
  ankle_pitch_1: -0.84
  ankle_pitch_2: 0.84
  ankle_pitch_3: 0.84
  ankle_pitch_4: -0.84

actions:
  parking:
    - steering: true
      q: q_parking_2
    - rotate_wheels
    - steering: false
      q: q_parking_3

  unparking:
    - rotate_wheels
    - steering: false
      q: q_unparking
    - steering: true
      q: q_homing

  boxing:
    - steering: true
      q: q_boxing_2
    - rotate_wheels
    - steering: false
      q: q_boxing_3

  unboxing:
    - rotate_wheels
    - steering: false
      q: q_unboxing

  homing:
    - steering: true
      q: q_homing

