
q_parking_2:
  hip_yaw_1: -0.75
  hip_yaw_2: 0.75
  hip_yaw_3: 0.75
  hip_yaw_4: -0.75
  hip_pitch_1: -1.57
  hip_pitch_2: 1.57
  hip_pitch_3: 1.57
  hip_pitch_4: -1.57
  knee_pitch_1: -2.4
  knee_pitch_2: 2.4
  knee_pitch_3: 2.4
  knee_pitch_4: -2.4
  ankle_pitch_1: -0.84
  ankle_pitch_2: 0.84
  ankle_pitch_3: 0.84
  ankle_pitch_4: -0.84
  ankle_yaw_1: 0.0
  ankle_yaw_2: 0.0
  ankle_yaw_3: 0.0
  ankle_yaw_4: 0.0

q_parking_3:
  ankle_pitch_1: -2.4
  ankle_pitch_2: 2.4
  ankle_pitch_3: 2.4
  ankle_pitch_4: -2.4

q_unparking:
  hip_pitch_1: -1.57
  hip_pitch_2: 1.57
  hip_pitch_3: 1.57
  hip_pitch_4: -1.57
  knee_pitch_1: -2.4
  knee_pitch_2: 2.4
  knee_pitch_3: 2.4
  knee_pitch_4: -2.4
  ankle_pitch_1: -0.84
  ankle_pitch_2: 0.84
  ankle_pitch_3: 0.84
  ankle_pitch_4: -0.84

q_homing: &q_homing
  hip_yaw_1: -0.75
  hip_yaw_2: 0.75
  hip_yaw_3: 0.75
  hip_yaw_4: -0.75
  ankle_pitch_1: -0.302
  ankle_pitch_2: 0.302
  ankle_pitch_3: 0.302
  ankle_pitch_4: -0.302
  hip_pitch_1: -1.25
  hip_pitch_2: 1.25
  hip_pitch_3: 1.25
  hip_pitch_4: -1.25
  knee_pitch_1: -1.56
  knee_pitch_2: 1.56
  knee_pitch_3: 1.56
  knee_pitch_4: -1.56
  j_arm1_1: 0.52
  j_arm1_2: 0.32
  j_arm1_3: 0.28
  j_arm1_4: -2.24
  j_arm1_5: 0.05
  j_arm1_6: -0.78
  j_arm2_1: 0.52
  j_arm2_2: -0.32
  j_arm2_3: -0.28
  j_arm2_4: -2.24
  j_arm2_5: -0.05
  j_arm2_6: -0.78
  torso_yaw: 0.0
  d435_head_joint: -0.6


q_homing_reversed_knee:  
  <<: *q_homing
  hip_yaw_1: -0.749
  hip_pitch_1: -0.088
  knee_pitch_1: 1.56
  ankle_pitch_1: 1.64
  ankle_yaw_1: 0.74
  hip_yaw_2: 0.749
  hip_pitch_2: 0.088
  knee_pitch_2: -1.56
  ankle_pitch_2: -1.64
  ankle_yaw_2: -0.74



q_boxing_2:
  hip_yaw_1: 0.0
  hip_yaw_2: 0.0
  hip_yaw_3: 0.0
  hip_yaw_4: 0.0
  hip_pitch_1: -1.57
  hip_pitch_2: 1.57
  hip_pitch_3: 1.57
  hip_pitch_4: -1.57
  knee_pitch_1: -2.4
  knee_pitch_2: 2.4
  knee_pitch_3: 2.4
  knee_pitch_4: -2.4
  ankle_pitch_1: -0.84
  ankle_pitch_2: 0.84
  ankle_pitch_3: 0.84
  ankle_pitch_4: -0.84
  ankle_yaw_1: 0.0
  ankle_yaw_2: 0.0
  ankle_yaw_3: 0.0
  ankle_yaw_4: 0.0

q_boxing_3:
  ankle_pitch_1: -2.4
  ankle_pitch_2: 2.4
  ankle_pitch_3: -0.74
  ankle_pitch_4: 0.74

actions:
  parking:
    - q_parking_2:
        steering: true
        change_steering: false
    - rotate_wheels
    - q_parking_3:
        steering: false
        change_steering: false

  unparking:
    - rotate_wheels
    - q_unparking:
        steering: false
        change_steering: true
    - q_homing:
        steering: true
        change_steering: false

  boxing:
    - q_boxing_2:
        steering: true
        change_steering: false
    - rotate_wheels
    - q_boxing_3:
        steering: false
        change_steering: false

  unboxing:
    - rotate_wheels
    - q_unparking:
        steering: false
        change_steering: true

  homing:
    - q_homing:
        steering: true
        change_steering: false

  homing_reversed_knee:
    - q_homing_reversed_knee:
        steering: true
        change_steering: false

